### ISSUE TITLE
milestone 생성 API 구현

### ISSUE THREAD

**Issue by 16010948** [boostcamp-2020/IssueTracker-06#13]
### milestone 생성 API 구현

- [x] milestone 생성 API 구현
  - [x] milestone 생성 라우터 생성
  - [x] milestone 생성 DB query 작성
  - [x] milestone 생성 DB 연동 business logic 작성
