### ISSUE TITLE
milestone 제거 API 구현

### ISSUE THREAD

**Issue by cyjo9603** [boostcamp-2020/IssueTracker-06#24]
### milestone 제거 API 구현

- [x] milestone 제거 API 구현
  - [x] milestone 제거 라우터 생성
  - [x] milestone 제거 DB query 작성
  - [x] milestone 제거 DB 연동 business logic 작성
