### ISSUE TITLE
milestone 상태 변경 API 구현

### ISSUE THREAD

**Issue by 16010948** [boostcamp-2020/IssueTracker-06#25]
### milestone 상태 변경 API 구현

- [x] milestone 상태 변경 API 구현
  - [x] milestone 상태 변경 라우터 생성
  - [x] milestone 상태 변경 DB query 작성
  - [x] milestone 상태 변경 DB 연동 business logic 작성
